### ISSUE TITLE
ServerClass labelSelectors ORs where it should AND?

### ISSUE THREAD

**Issue by bzub** [talos-systems/sidero#288]
The [docs](https://www.sidero.dev/docs/v0.1/configuration/serverclasses/#server-classes) do not specifically mention expected logical behavior for labels in a single element under `labelSelectors`, but it seems intuitive to me that they would be ANDed. This is not the case.

How to reproduce:
```yaml
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: uuid-server-a
  labels:
    matchingValue: value
    differingValue: value-a
spec:
  accepted: true
---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: uuid-server-b
  labels:
    matchingValue: value
    differingValue: value-b
spec:
  accepted: true
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: serverclass-a
spec:
  qualifiers:
    labelSelectors:
    - matchingValue: value
      differingValue: value-a
---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: serverclass-b
spec:
  qualifiers:
    labelSelectors:
    - matchingValue: value
      differingValue: value-b
```

```
❯ kubectl get serverclasses
NAME            AVAILABLE                           IN USE
serverclass-a   ["uuid-server-b","uuid-server-a"]   []
serverclass-b   ["uuid-server-b","uuid-server-a"]   []
```

Might get replaced in a new API version (https://github.com/talos-systems/sidero/issues/282) but the currently behavior seems like a bug so might warrant a fix.
