### ISSUE TITLE
exec format error when setting environmentRef on ServerClass

### ISSUE THREAD

**Issue by charlie-haley** [talos-systems/sidero#624]
The initial boot works, it boots into Talos then wipes `/dev/sda` as per my config patch in the `ServerClass`, I also have an `environmentRef` in the `ServerClass` which references my ARM environment
<details>
<summary>environment - default-arm64.yaml</summary>

```yaml
---
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: default-arm64
  namespace: default
spec:
  kernel:
    url: "https://github.com/talos-systems/talos/releases/download/v0.13.2/vmlinuz-arm64"
    args:
      - console=tty0
      - console=ttyS1,115200n8
      - consoleblank=0
      - earlyprintk=ttyS1,115200n8
      - ima_appraise=fix
      - ima_hash=sha512
      - ima_template=ima-ng
      - init_on_alloc=1
      - initrd=initramfs.xz
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - random.trust_cpu=on
      - slab_nomerge=
      - talos.config=http://192.168.1.215:8081/configdata?uuid=
      - talos.platform=metal
  initrd:
    url: "https://github.com/talos-systems/talos/releases/download/v0.13.2/initramfs-arm64.xz"
```
</details>

<details>
<summary>serverclass - default-arm64.yaml</summary>

```yaml
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: default-arm64
spec:
  environmentRef:
    namespace: default
    name: default-arm64
  qualifiers:
    cpu:
      - manufacturer: Broadcom
        version: BCM2711 (ARM Cortex-A72)
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
```
</details>

Once it reboots after wiping the disk, it attempts to boot again over PXE, but this time returns an `Exec format error` which is leading me to believe it's trying to boot the wrong architecture, just not entirely sure why.

This is the log from the Pi when it tries to boot for the second time:
```
  >>Start PXE over IPv4. 
  Station IP address is 192.168.1.17

  Server IP address is 192.168.1.215 
  NBP filename is ipxe-arm64.efi 
  NBP filesize is 990944 Bytes 
Downloading NBP file...

  NBP file downloaded successfully. 
iPXE initialising devices...ok

iPXE 1.21.1 sidero -- Open Source Network Boot Firmware -- http://ipxe.org
Features: DNS HTTP HTTPS ¡SCSI TFTP SRP AoE EFI Menu
Waiting for link-up on neto...... ok
Configuring (neto dc:a6:32:2f:a6:05) ...... ok
http://192.168.1.215:8081/ipxe….. ok /env/default/vnlinuz… ok
Could not select: Exec format error (http://ipxe.org/2e008081)
Could not boot: Exec format error (http://ipxe.org/2e008081)

  >>Start PXE over IPv6.
```

If I move the environmentRef from the ServerClass to the Server, it seems to boot fine

**Comment by charlie-haley** [comment]
I also noticed the same issue when trying to configure `configPatches` on the `ServerClass` for the install disk. Is it because my servers were assigned to multiple `ServerClass`'s?

**Comment by frezbo** [comment]
@charlie-haley having it assigned to multiple serverclasses shouldn't matter, since it anyways would match the default `any` class

Here's my environment and serverclass specs

<details>
<summary>environment</summary>

```yaml
apiVersion: metal.sidero.dev/v1alpha1
kind: Environment
metadata:
  name: rpi4
spec:
  initrd:
    url: https://github.com/talos-systems/talos/releases/download/v0.11.5/initramfs-arm64.xz
  kernel:
    args:
    - console=ttyAMA0,115200
    - consoleblank=0
    - earlyprintk=ttyAMA0,115200
    - ima_appraise=fix
    - ima_hash=sha512
    - ima_template=ima-ng
    - init_on_alloc=1
    - initrd=initramfs.xz
    - nvme_core.io_timeout=4294967295
    - printk.devkmsg=on
    - pti=on
    - random.trust_cpu=on
    - slab_nomerge=
    - talos.config=http://192.168.15.159:8081/configdata?uuid=
    - talos.platform=metal
    url: https://github.com/talos-systems/talos/releases/download/v0.11.5/vmlinuz-arm64
```
</details>

<details>
<summary>serverclass</summary>

```yaml
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: rpi4-cp
spec:
  environmentRef:
    name: rpi4
  configPatches:
  - op: replace
    path: /machine/install
    value:
      disk: /dev/sda
      extraKernelArgs:
      - console=ttyAMA0,115200
  qualifiers:
    systemInformation:
      - version: 10000000c26932f8
```
</details>

from the logs it seems that it's not picking the right environment. The only difference is see is the `namespace` field under the `environmentRef` (it's not needed at all)

also can you provide the output of `kubectl get serverclasses` and `kubectl get servers`
