### ISSUE TITLE
generated talosconfig doesn't contain endpoints

### ISSUE THREAD

**Issue by smira** [talos-systems/sidero#70]
Not sure if this should be bootstrap controller project issue, but I'll report it here for easier access.

What I see in `talosconfig` resource:

```yaml
  status:
    dataSecretName: management-cluster-cp-46k74-bootstrap-data
    ready: true
    talosConfig: |
      context: management-cluster
      contexts:
        management-cluster:
          target: ""
          ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJIekNCMHFBREFnRUNBaEIxemJ3OTliT3pPT0U4OUFLMU5tVkFNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU1EQTVNVGd4TmpBNE1UQmFGdzB6TURBNU1UWXhOakE0TVRCYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBR3J5VmU1SGVsVU11MTRwR2FFZ0kyVzJEdGRyV0E0d0dla2NGCjBsbkNOOVdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFGQmdNclpYQURRUUQzYlkzMkVqSnprUW9kWTZqVAo2Wlg5TXRubkdrM2dnMS9GaVd4cmEvNU96R1RnQXdhK3VzS1ZybEdpaDFjSnZzd3VxWHZyZVRScHh4N0xnU2hqClBCUUQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
          crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJHakNCemFBREFnRUNBaEF4WkJCL2orbEVzYkR6V1FINTd2RXNNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU1EQTVNVGd4TmpBNE1UQmFGdzB6TURBNU1UWXhOakE0TVRCYU1Bc3hDVEFIQmdOVgpCQW9UQURBcU1BVUdBeXRsY0FNaEFKVWVXditoejJ2S2RZbDhRbUdMdlBOc0M1WU14Wm9hdEl1VkovMENyMjg3Cm8wSXdRREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUYKQndNQ01BOEdBMVVkRVFRSU1BYUhCSDhBQUFFd0JRWURLMlZ3QTBFQUtmSnArcjlZdEprNHhBZm1NUFcrUmtlTwpuNGFiRDJjVUhJeEVDR2FIMlFOY1RNaDR6WHhOWnQzZi9WTEhac3lRL1dMaU0ySmdsdXIyM0d5QUJma3dDdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
          key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJRkNTUUwzZFlGY05IaDR6c2FEUWxXb3cwMldkME92REpBeGN0RzIvWXFCRwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
```

First of all, `target` is deprecated for a long time.

Second, modern config contains endpoints, e.g.:

```yaml
contexts:
    sfyra:
        endpoints:
            - 172.24.0.2
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEJ6dXgzQS9XSkNTLzViclI5N1E5WXVNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU1EQTVNVGd4TmpBeU5UQmFGdzB6TURBNU1UWXhOakF5TlRCYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBQ2dMaU5HSzRPVnhBeVpPSmJUMDJNTmpENXNxTlJ1QitlODdHCk5Ca3ZOaitqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVdnZqSnUrMlhrQzBYZk5PWgp3aER6OTRKRU9BZ3dCUVlESzJWd0EwRUFBYjlJQTR6b0pIZ0RXcDMvZklLbWdacmV6elMzSGFvcFhlYWw1VVAvCmpkVzMrRGpKb1dKbWtzSkdzeE1TbmlxMUNwT1A1YmpzZHgrQnJDQ0V5eUhXQVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQRENCNzZBREFnRUNBaEVBckkyYmJ2TnlyU2tjaDNRRVg4OHVSakFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qQXdPVEU0TVRZd01qVXdXaGNOTXpBd09URTJNVFl3TWpVd1dqQUxNUWt3QndZRApWUVFLRXdBd0tqQUZCZ01yWlhBRElRQzF1WU5pOHBzYXBFcWpCRzhXbHZOMzhFM3U1YlBRMTlEaWhIdUo5RVhyCllLTmpNR0V3RGdZRFZSMFBBUUgvQkFRREFnZUFNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUYKQlFjREFqQWZCZ05WSFNNRUdEQVdnQlMrK01tNzdaZVFMUmQ4MDVuQ0VQUDNna1E0Q0RBUEJnTlZIUkVFQ0RBRwpod1IvQUFBQk1BVUdBeXRsY0FOQkFNOWg1U1hFSzNvV0NlYzhhbWt2WXlNWHFBaCt5RXVWbzBhaStJak9yeDhwCjA0QlNRcFlYbXM1MlZpWHNqdS9TM01IWnZjZHNrSnFPNTBqM3R0a2xoZ009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSjZBTmNXait2c0EyYXFQTTFDNjQ5YVlHTDFjQ2NMZ1RpdUJCTGhBNEVUbgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
```

Without `endpoints` config is not usable directly
