### ISSUE TITLE
machine Spec doesn't have any IP information

### ISSUE THREAD

**Issue by smira** [talos-systems/sidero#71]
Sidero:

```
status:
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2020-09-18T16:13:09Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2020-09-18T16:08:15Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2020-09-18T16:13:09Z"
      status: "True"
      type: InfrastructureReady
    infrastructureReady: true
    lastUpdated: "2020-09-18T16:13:09Z"
    nodeRef:
      apiVersion: v1
      kind: Node
      name: pxe-2
      uid: e6c0e820-2287-4e8d-95a1-76c1e3a541de
    observedGeneration: 3
    phase: Running
```

while for AWS/GCP we can have `.spec.addresses`:

```
MASTER_IP=$(${KUBECTL} --kubeconfig /tmp/e2e/docker/kubeconfig get machine -o go-template --template='{{range .status.addresses}}{{if eq .type "ExternalIP"}}{{.address}}{{end}}{{end}}' ${FIRST_CP_NODE})
```
